switch OR statements
to prevent java.lang.NoSuchMethodError: 'boolean
org.eclipse.lsp4e.LanguageServerWrapper.startupFailed()'
when vendors has yet updated LSP4E. This is only a small workaround
because the exception is still thrown when the LS config contains errors
and the startup fails.